- name: condition in ansible file
  hosts: all
  tasks: 
    - name: This is a condition in ansible file
      debug:
        msg: this task is running on ec2-user
      when: ansible_distribution == "Amazon"
