- name: gathering facts
  hosts: all
  become: yes
  tasks: 
    - name: Ansible hosts info 
      debug: 
        msg: 
          - "Ansible distro is {{ansible_distribution}}"
          - "Ansible family is {{ansible_os_family}}"
          - "Ansible python version is {{ansible_python_version}}"
          - "Ansible bios date is {{ansible_bios_date}}"
          - "Ansible distro file is {{ansible_distribution_file_path}}"
          - "Ansible domain is {{ansible_domain}}"
          - "Ansible machine is {{ansible_machine_id}}"
          - "Ansible user dir is {{ansible_user_dir}}"
          - "Ansible discovered interpreter is {{discovered_interpreter_python}}"
          