- name: gathering facts
  hosts: all
  become: yes
  tasks: 
    - name: Ansible hosts info 
      debug: 
        msg: 
          - "Ansible distro is {{ansible_distribution}}"
          - "Ansible distro family is {{ansible_os_family}}"