- name: gathering facts
  hosts: all
  become: yes
  tasks: 
    - name: Ansible hosts info 
      debug: 
        msg: 
          - "Ansible distro is {{ansible_distribution}}"
          - "Ansible distro family is {{ansible_os_family}}"
          - "Ansible distro is {{ansible_python_version}}"
          - "Ansible distro date is {{ansible_bios_date}}"
          - "Ansible distro file is {{ansible_distribution_file_path}}"
          - "Ansible distro domain is {{ansible_domain}}"
          - "Ansible machine is {{ansible_machine_id}}"

          