- name: ignoring errors files
  hosts: all
  tasks:
    - name: ignore error
      shell: ps_aux | grep java | grep -v java
      ignore_errors: yes

    - name: run the process
      debug:
        msg: ignoring the process  