- name: package installation using playbook
  hosts: all
  become: yes
  tasks:
    - name: httpd install
      ansible.builtin.package:
        name: tree
        state: present

    - name: Install one specific version of Apache
      ansible.builtin.yum:
        name: httpd-2.2.29-1.4.amzn1
        state: present    