- name: template hosting in playbook 
  hosts: all
  become: yes
  tasks: 
    - name: package installation
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
        - httpd
        - wget
        - unzip

    - name: download template
      ansible.builtin.get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page287/cycle.zip     
        dest: /var/www/html/
        remote_src: true

    - name: unzip template
      ansible.builtin.unarchive:
        src: /var/www/html/cycle.zip
        dest: var/www/html/
        remote_src: true

    - name: restart httpd services
      shell: systemctl restart httpd
