- name: variable playbook 
  hosts: all 
  vars: 
    url: www.global-var.com
  vars_files:
    - filevars.yaml
  tasks: 
    - name: variable print 
      debug: 
        msg: "{{url}}"
      vars: 
        url: www.local-var.com

  