- name: variable playbook 
  hosts: all 
  vars: 
    url: www.global-var.com
  vars_files:
    - filevars.yaml
  tasks: 
    - name: task1 print 
      debug: 
        msg: "{{url}}"
      vars: 
        url: www.local-var.com

    - name: task2 print
      debug:
        msg: "{{url}}"
        
    - name: task3 print
      debug:
        msg: "{{url1}}"

    - name: task4 print
      debug:
        msg: "{{url2}}"

    - name: task5 print
      debug:
        msg: "{{url3}}"    